### ISSUE TITLE
misspacement of manipulator code

### ISSUE THREAD

**Issue by SzymonDzw** [TurtleRover/firmware-shield#9]
Wtf does manipulator do in motors.h file?

**Comment by mrozsebastian** [comment]
> Wtf does manipulator do in motors.h  <

Don't be rude, don't use Wtf :) It's legacy issue, resolved in : [commit](https://github.com/TurtleRover/firmware-shield/commit/fb800ac4ea8a966ace9634ec0c3d336490a8eacb)
